---
- name: inatall package 
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - git
    - python3
    - python3-pip 
    - python3-dev

- name: clone project 
  git:
    repo: "{{ git_addr }}"
    dest: /srv/{{ project_name }}



- name: install virtual env 
  pip:
    executable: pip3
    name: virtualenv
    state: latest
